---
title: "States Data"
author: "Dominic Skinnion"
date: "7/9/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
options(scipen = 999)
```

```{r data read in, echo = FALSE}
us <- read.csv(file = "us.csv")
states <- read.csv(file = "us-states.csv")
counties <- read.csv(file = "us-counties.csv")
census <- read.csv(file = "census2019est.csv")
election_pres_2016 <- read.csv(file = "1976-2016-president.csv")
regions <- read.csv(file = "state_regions_and_divisions.csv")
```

```{r clean up census, echo = FALSE}
census <- census %>%
  select(NAME, POPESTIMATE2019) %>%
  mutate(state = ifelse(NAME == "Puerto Rico Commonwealth", "Puerto Rico", NAME)) %>%
  mutate(popest2019 = POPESTIMATE2019) %>%
  select(state, popest2019)
```

```{r adding new cases, echo = FALSE}
states_list <- unique(states$state)

make_state_df <- function(state_name){
  
  states <- states %>%
    filter(state == state_name) %>%
    mutate(cases_yesterday = lag(cases)) %>%
    mutate(new_cases = cases - cases_yesterday) %>%
    mutate(deaths_yesterday = lag(deaths)) %>%
    mutate(new_deaths = deaths - deaths_yesterday)
}

states_with_new_cases <- map_df(states_list, make_state_df)
states_with_new_cases <- states_with_new_cases %>%
  mutate_all(~replace(., is.na(.), 0))
```

# first attempt at making state dataframes... might be useful if I need individual dfs for each state
# ```{r state calculations, echo = FALSE}
# states_list <- unique(states$state)
# 
# make_state_df <- function(state_name){
#   
#   object <- states %>%
#     filter(state == state_name) %>%
#     mutate(cases_yesterday = lag(cases)) %>%
#     mutate(new_cases = cases - cases_yesterday) %>%
#     mutate(deaths_yesterday = lag(deaths)) %>%
#     mutate(new_deaths = deaths - deaths_yesterday)
#   
#   assign(paste(state_name), data.frame(object), envir = .GlobalEnv)
# }
# 
# map_df(states_list, make_state_df)
# ```

```{r merge census and covid, echo = FALSE}
states_with_pop <- inner_join(states_with_new_cases, census, by = "state")
```

```{r adding per capita calcs, echo = FALSE}
states_with_pc <- states_with_pop %>%
  mutate(cases_pc = cases / popest2019) %>%
  mutate(new_cases_pc = new_cases / popest2019) %>%
  mutate(deaths_pc = deaths / popest2019) %>%
  mutate(new_deaths_pc = new_deaths / popest2019)
```

```{r sample data viz, echo = FALSE}
states_with_pc %>%
  filter(state %in% c("Massachusetts", "Virginia", "California")) %>%
  ggplot(aes(x = date, y = new_cases_pc, group = state, color = state)) +
    geom_line()
```

```{r election 2016 pres, echo = FALSE}
election_pres_2016_hrc <- election_pres_2016 %>%
  filter(year == 2016,
         office == "US President",
         party == "democrat",
         writein == "FALSE") %>%
  mutate(hrc_votes = candidatevotes) %>%
  select(year, state, candidate, party, hrc_votes, totalvotes)

election_pres_2016_djt <- election_pres_2016 %>%
  filter(year == 2016,
         office == "US President",
         party == "republican",
         writein == "FALSE") %>%
  mutate(djt_votes = candidatevotes) %>%
  select(year, state, candidate, party, djt_votes, totalvotes)

election_pres_2016_djt_vs_hrc <- inner_join(election_pres_2016_djt, 
                                            election_pres_2016_hrc, 
                                            by = c("year", "state", "totalvotes"))

election_pres_2016_djt_vs_hrc <- election_pres_2016_djt_vs_hrc %>%
  select(state, djt_votes, hrc_votes, totalvotes) %>%
  mutate(pct_djt = djt_votes / totalvotes, pct_hrc = hrc_votes / totalvotes) %>%
  mutate(winner = ifelse(djt_votes > hrc_votes, "Trump", "Clinton"))
```

```{r joined covid with election, echo = FALSE}
states_and_election <- inner_join(states_with_pc, election_pres_2016_djt_vs_hrc, by = "state")
```

```{r added regions, echo = FALSE}
regions <- regions %>%
  mutate(state = State, 
         region = Region, 
         division = Division) %>%
  select(state, region, division)

states_and_election <- inner_join(states_and_election, regions, by = "state")
```


```{r data exploration, echo = FALSE}
states_and_election %>%
  ggplot(aes(x = date, y = new_cases, fill = winner)) +
      geom_bar(stat = "identity", position = position_dodge())
```

```{r states total by winner, echo = FALSE}
by_winner <- states_and_election %>%
  group_by(date, winner) %>%
  summarise(total_new_cases = sum(new_cases),
            avg_new_cases = mean(new_cases),
            avg_new_cases_pc = mean(new_cases_pc))

by_winner %>%
  ggplot(aes(x = date, y = avg_new_cases_pc, fill = winner)) +
    geom_bar(stat = "identity", position = "fill")

by_winner %>%
  ggplot(aes(x = date, y = total_new_cases, fill = winner)) +
    geom_bar(stat = "identity", position = "fill")
```

```{r states total by region, echo = FALSE}
by_region <- states_and_election %>%
  group_by(date, region) %>%
  summarise(total_new_cases = sum(new_cases),
            avg_new_cases = mean(new_cases),
            avg_new_cases_pc = mean(new_cases_pc))

by_region %>%
  ggplot(aes(x = date, y = avg_new_cases_pc, fill = region)) +
    geom_bar(stat = "identity", position = "fill")

by_region %>%
  ggplot(aes(x = date, y = total_new_cases, fill = region)) +
    geom_bar(stat = "identity", position = "fill")

```

```{r states total by region and winner, echo = FALSE}
by_region_and_winner <- states_and_election %>%
  group_by(date, region, winner) %>%
  summarise(total_new_cases = sum(new_cases),
            avg_new_cases = mean(new_cases),
            avg_new_cases_pc = mean(new_cases_pc))

by_region_and_winner %>%
  ggplot(aes(x = date, y = total_new_cases, fill = winner)) +
    geom_bar(stat = "identity", position = "fill") +
    facet_wrap(~region)
```

